### ISSUE TITLE
remove Mouse events from commandline

### ISSUE THREAD

**Issue by f0wl** [f0wl/inMediasREs#4]
At the moment Mouse events (e.g. Left/Right Click, Release) are tracked by termui and displayed in the commandline box at the bottom. This is unwanted and should be fixed.

**Comment by WelverinRaven** [comment]
I'll look into it

**Comment by WelverinRaven** [comment]
Hey, I'm having trouble getting your project to run. Do I have to setup some environment variables beforehand or give it some arguements? 
`go run inMediaREs.go` produces a `panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.main()
       <redacted>/github.com/inMediasREs/inMediasRes.go:170 +0x3f67
exit status 2`
Debugging also does not work...

Providing some Info how to start it could also go into the README.md

**Comment by f0wl** [comment]
Yeah debugging it (especially with VS Code) is a piece of work on its own :D As for this error the program expects a filename as an argument (sorry for not mentioning that). For testing you can use this non-malicious [sample ELF File](https://github.com/eliben/pyelftools/blob/master/examples/sample_exe64.elf)

**Comment by WelverinRaven** [comment]
I think I got it. And your Tool looks interesting, I'd like to get it to work on my machine :grin:
